gui-doc/scribblings/gui/gui.scrbl, gui-doc/scribblings/gui/init.scrbl, gui-lib/info.rkt
Previously they were part of the base repo.
Combines with PR https://github.com/racket/racket/pull/1387
=> Move docs for racket/gui/init and racket/gui/interactive

gui-doc/scribblings/gui/win-overview.scrbl
a small typo fix
flushing to the screen can be starved if flushing is frequently suspend.
changed to
flushing to the screen can be starved if flushing is frequently suspended.
=> correct small typo in 'Animation in Canvases'

gui-lib/mred/private/wx/cocoa/slider.rkt
It would occasionally drop the last digit in the message field.
This turned out to be a bug where the number, while smaller, was wider.
For example:
11111
10101
In variable width fonts the second one will be wider
=> Fixes bug in slider%

gui-lib/mred/private/wx/gtk/window.rkt
This fixes the crazy fast scrolling that has been present on GTK since commit 2c5b1480f4f7b39e84548d2a618e30525178a364.
=> GTK+: accumulate small scroll events into appropriate wheel events

gui-lib/framework/private/frame.rkt
This PR fixes an internal error in DrRacket (reproduced in Windows and Linux) but I'm unsure if I changed the right code.
The following sequence produces the error:
1) Edit -> Find
2) make sure search box is empty
3) Edit -> Replace All
I added a guard in `replace-all` in `gui-lib/framework/private/frame.rkt`.
However, the error comes from `do-find-string` in https://github.com/racket/gui/blob/master/gui-lib/mred/private/wxme/text.rkt#L3780, which seems assume a non-empty string input, but I guessed that this is intended since the function seems to be called from many sources and I was unable to produce the error from these other paths. (Although the non-empty string requirement should be documented in the public methods.)
Did I change the right code?
The full error output is:
``` …
```
=> fix DrRacket internal error: replace-all with empty str [needs-review]

gui-lib/mred/private/wx/gtk/cursor.rkt
Currently if I run on wayland if I try to run gui racket programs they just crash and I get the following error:
Gdk-Message: Unable to load arrow from the cursor theme [[this is from GTK, not Racket]]
GdkCursor->C: argument is not non-null `GdkCursor' pointer
argument: #f
This small edit makes racket not crash (though I still get the Gdk-Message, I'm not sure what causes that), and gui Racket programs run just fine.  Allowing the cursor to be nullable doesn't seem to cause any problems from a brief look through cursor.rkt, but I'm no expert on racket/gui or on GTK.
=> make GdkCursor nullable

gui-doc/scribblings/framework/text.scrbl, gui-lib/framework/private/text.rkt, gui-test/framework/tests/text.rkt
This pull request reimplements move/copy-to-edit using two new methods (move-to and copy-to) and adds unit tests and random testing for these methods. to Reimplement move/copy-to-edit to fix bug when edits are made to the same object.
=> Reimplement move/copy-to-edit to fix bug when edits are made to the same object.

gui-doc/scribblings/framework/color.scrbl
Fixed the order of the two extra return values for get-token: the 'new mode' and 'backup distance' were swapped.
=> Fix for the documentation of get-token

gui-lib/framework/private/main.rkt
match-define is in the define-like forms, it makes sense to have
match-define-values as well.
=> Add match-define-values to indentation defaults.

gui-lib/framework/private/text.rkt
At the moment if a user refuses to save a file with non-textual widgets
using wxme, DrRacket will just save the file as flattened text. This leads
to lost data, and makes otherwise valid racket files invalid.
This patch prevents the file from loosing that data on saving. Namely,
if a user:
1. Opened a file as a text file.
2. Added non-textual snips to the file.
3. Has in their preferences to warn before changing the file type.
4. Saves the file but refuses to change the type.
then DrRacket will not save the file because it cannot
do so.
=> Fix bug where DrRacket could loose data when saving.

gui-lib/mred/private/wx/gtk/window.rkt
From https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-process-all-updates
> gdk_window_process_all_updates has been deprecated since version 3.22 and should not be used in newly-written code.
Calls to this function seem to add significant overhead when, for example, drawing text in a simple text editor. There seems to be no benefit to this call, as removing it still will have things be redrawn on flush-display via gdk_display_flush. I am not sure if there are legacy reasons for the call to gdk_window_process_all_updates, but it would be great to not have this call if it is not necessary.
=> Remove call to gdk_window_process_all_updates

gui-lib/framework/private/racket.rkt
Currently, in at-exp languages, a double click on text selects the line not the word. This changes that.
=> make scribble double click select words, not lines

gui-doc/mrlib/scribblings/arrow-toggle-snip.scrbl, gui-doc/mrlib/scribblings/expandable-snip.scrbl, gui-doc/mrlib/scribblings/mrlib.scrbl, gui-lib/mrlib/arrow-toggle-snip.rkt, gui-lib/mrlib/expandable-snip.rkt, gui-lib/mrlib/hierlist.rkt, gui-lib/mrlib/hierlist/hierlist-unit.rkt, gui-lib/mrlib/syntax-browser.rkt
Adds two new snip classes:
- `arrow-toggle-snip%` is a toggle control. Uses include syntax snips and hierlist lists. This PR changes the snip to scale with the style's font size.
- `expandable-snip%` extracts the toggle-for-details part of syntax snips.
=> factor expandable-snip etc out of syntax-browser snip

gui-lib/mred/private/wx/cocoa/canvas.rkt
`removeChildWindow` doesn't actually hide the blit window so call `orderOut:` on it as well.
Fixes issue #94
=> Fix blit windows hanging around when suspended

gui-lib/mred/private/wx/cocoa/frame.rkt
We already hide the fake root when it's first designated
(in designate-root-frame), but macOS can make it visible
again when no other windows exist and the application is
reactivated. So hide it in response to windowDidBecomeMain.
Fixes racket/drracket#202.
=> macOS: hide the fake root frame when it becomes main

gui-lib/info.rkt
Several places make references to (lib "myfilename.png" "icons"),
where that file is not in gui-lib/icons, but in the icons package.
=> gui-lib: add dependency on icons

gui-lib/mred/private/wxme/text.rkt
1) Check that `m` is small enough instead of waiting until the last character to exit. (This is useful for long `word`s.)
2) When a `#f` is found in the kmp-table, advance the position of `m` to the current position `m+i` instead of just advancing it once to `m+1`.
3) I'm worried about the 0 length string. I'm not sure if the result when `word=""` is `#t` or `#f` or what. I guess that case is filtered somewhere, but I broke that corner case in my first version of racket/string.rkt.
4) I think that the `(loop (+ m 1) 0))` in the lines 3790 and 3797 can be changed also to something like the code in like 3800 `[else (define t-i ...) ...)`  but I'm not sure if the kmp table needs an special entry for that case or the last entry can be used. I still have to think more the details of this.
I'm …
=> improve KMP in wxme\text

.travis.yml, gui-test/tests/gracket/wxme.rkt
This makes Travis-CI test wxme.rkt, but it has a few problems.
I had to use the minimal installer of Racket because the normal installer installs the default version of `gui-lib` and I wanted to use the version in the current branch. I tried using `raco pkg remove` and `raco pkg install` to replace it, but I get an error. I tried other combinations without success, so I finally decided to install the minimal version and then all the packages I need, but it is slower.
Another problem is that I can't install the `gui-test` package because it links to too many additional packages, so the installation is too slow and I even get a strange error. So ... I'm using the wxme.rkt file from the folder without installing the package. It's not a good idea but it works. In particular this is bad if we …
=> Test wxme.rkt in Travis-CI (draft)

tex-table/tex-table.rkt
=> use correct character for longrightarrow

gui-lib/framework/private/text.rkt, gui-test/framework/tests/text.rkt
If the backspace key has been pressed during autocompletion, some following characters would be unexpectedly deleted when the selected string is inserted, because the widen-possible-completions method doesn't adjust the value of word-end-pos.
=> fix mismatched word-end-pos for autocomplete

gui-lib/mred/private/wx/gtk/menu.rkt
Originally I found the issue reported here : https://github.com/MatrixForChange/files-viewer/issues/28 , but then I found it is a common issue of the gtk backend of racket/gui. Screenshots is available in that issue.
If I understand correctly (according to https://developer.gnome.org/gtk3/stable/GtkMenu.html#GtkMenuPositionFunc), only combobox-like things would need to set the push_in to true, and removing that line seems to be a solution.
Feel free to close this if I actually missed something.
=> fix scroll position of popup menus when on the bottom of monitor

gui-lib/framework/private/main.rkt
This is because splicing-parameterize is now part of the
racket/splicing library.
=> Add splicing-parameterize to default indentation

.travis.yml
There was some change in Travis-ci, and the test are failing. This is the new recomended method to start xvfb.
=> Fix xvfb in travis-ci

gui-doc/scribblings/gui/image-snip-class.scrbl, gui-test/tests/gracket/issue-119.rkt, gui-test/tests/gracket/test.rkt, gui-test/tests/issue-119.rkt
Update the signature of the `other-equal-to?` method for `image-snip%`, since
it now accepts a `snip%` as an argument.  Also added test cases for checking
that `image-snip%` objects can be compared with other objects.
This commit corresponds to the fix for issue #119, which is in the racket/snip
package.
=> Update contract on image-snip% other-equal-to? method (racket/gui#119)

gui-lib/mred/private/wx/cocoa/window.rkt
I was looking at the scrolling behavior changes in db864a46597ee618ba55363bbf8bf4b6ebda90a7 and my little linter tool picked up this problem.
=> pass the correct value to set-wheel-steps

gui-lib/mred/private/wx/cocoa/window.rkt
I noticed that `NSScrollView`-based widgets stopped scrolling on master since db864a46597ee618ba55363bbf8bf4b6ebda90a7. I still haven't fully wrapped my head around `do-key-event` so feel free to scrap this if there's a better approach.
You can use this script to reproduce the issue:
```racket
#lang racket/base
(require racket/gui)
(define frame
(new frame%
[label "Test"]
[width 500]
[height 500]))
(define lb
(new list-box%
[parent frame]
[label #f]
[choices (make-list 120 "a")]))
(send frame show #t)
```
=> bubble up unhandled scroll events

gui-lib/framework/private/racket.rkt, gui-test/framework/tests/racket.rkt
This bug fix follows a discussion with Robby on slack #drracket. The bug was that when typing a closing parenthesis at the end of line of a line comment, smart-skip may skip to the next closing parenthesis on the next line, because the lexer believes it is already outside the line comment
(this behaviour is correct for nested comments `#|...|#` but not for line comments `; ...`). See the two new test cases.
The current proposal is a tradeoff between simplicity, bug fix, and specificity to the racket language.
Note that for homogeneity (and robustness), I also changed in the same function the previous check for beginning of strings and beginning of comments (where characters are actually not inserted in the string or comment) to follow the same pattern I use for the bug fix, which is to …
=> fix paren insertion at eol of line comment

gui-test/tests/gracket/editor.rktl
Fixes intermittent DrDr errors like this:
http://drdr.racket-lang.org/54174/cs/racket/share/pkgs/gui-test/tests/gracket/tmp98
=> Avoid creating files in the current directory in editor.rktl tests.

gui-doc/scribblings/gui/system-menu-funcs.scrbl
"when … and user clicks" -> "when … and a user clicks"
=> docs: grammar fix

gui-doc/scribblings/framework/color.scrbl, gui-lib/framework/private/color.rkt, gui-lib/framework/private/racket.rkt, gui-test/framework/tests/color-text.rkt, gui-test/framework/tests/racket.rkt
Addresses racket/drracket#201 regarding parens as well as analogous
behavior for " and | characters.
=> adds auto-delete for some characters created by auto-parens

gui-lib/mred/private/wxme/text.rkt, gui-test/tests/gracket/pr195.rkt
This is a fix for #192, and the example in that issue works fine with this change.
Calling `set-padding`, will result in a call to `recalc-lines` (via calls to `needs-update` -> `continue-update` -> `redraw`).
Before the `text%` objects is shown and the canvas dimensions are computed, the `max-width` will be 3, and when the left, right padding and `CURSOR-WIDTH` are subtracted from it, the remaining width will be negative.  As a result of this, `mline-update-flow` will always return `#t`, so the loop never terminates.
I changed the code to calculate the final width and checking that result to be positive.
* I am unsure why `max-width` was 3 before the canvas was shown (using the example from #192), I was expecting it to be 0
* ~I could not find the definition of `mline-update-flow` using …
=> Ensure that the canvas width is sufficient for reflowing lines (fix for #192)

gui-doc/scribblings/framework/frame.scrbl, gui-doc/scribblings/framework/framework.scrbl, gui-doc/scribblings/framework/srcloc-snip.scrbl, gui-doc/scribblings/framework/text.scrbl, gui-lib/framework/framework-unit.rkt, gui-lib/framework/main.rkt, gui-lib/framework/private/frame.rkt, gui-lib/framework/private/sig.rkt, gui-lib/framework/private/srcloc-snip.rkt, gui-lib/framework/private/text-port.rkt, gui-lib/framework/private/text.rkt, gui-lib/framework/srcloc-snip.rkt, gui-lib/framework/wxme-srcloc-snip.rkt, gui-lib/info.rkt
- make text:ports-mixin port accept markup objects as special values
- add srcloc-snip% class to create clickable links
- add find-editor method to frame:editor<%> for use in above
NOTE: Needs to be applied together with the pull request coming up for `drracket`
=> Enable writing markup to text:ports-mixin texts:

.github/CONTRIBUTING.md, README.md
Adds a note to the README and a `.github/CONTRIBUTING.md`, both of them simply linking to the file in racket/racket
Probably a better approach than #211 and a _much_ better branch name
Closes #210
=> Add a link to the contributing guidelines

gui-lib/mred/private/wxwindow.rkt
guard from using mouse-event methods on a key-event
close [drracket/issues/466](https://github.com/racket/drracket/issues/466)
=> guard mouse-event

gui-lib/mred/private/wxme/editor-canvas.rkt
Fix for https://github.com/racket/drracket/issues/147
When printing the definitions area in DrRacket, it makes sense to have
the viewable range be essentially infinite, so all of the line numbers
in the file are always printed.  Currently it is hard-coded at a size
of 10000x10000, which turns out to not be high enough.
This patch changes the size to a very large number (1e50), and in my
tests it fixes the linked bug.
=> Increase view used while printing

gui-lib/mred/private/wx/cocoa/list-box.rkt
Here's what the following program looks like
```racket
#lang racket/gui
(define f (new frame% [label "LB"]))
(define l (new list-box% [parent f] [label #f] [choices '("a" "b")]))
(send f show #t)
```
before this change:
and after:
=> list-box: fix cell higlighting on macOS

gui-lib/info.rkt
The improvement of the layering support (16147c5e5a) depends
on the new API `get-gui-bin-extra-search-dirs` introduced
in Racket v8.2 (racket/racket@dfbb7040aa).
=> Bump gui-lib dependency to 8.2.0.1

gui-lib/mred/private/wx/cocoa/choice.rkt
`NSPopUpButton` checks for duplicates before inserting new items, which
means code like
(new choice% [choices '("a" "a" "b")] ...)
would previously panic with
"Invalid parameter not satisfying: index <= [_item Array count]"
because the implementation would attempt to insert the "b"
label at position 2, thinking two "a" labels were inserted when only
one was.
This change uses the underlying NSMenu methods to append items since
they don't check for duplicates.  In addition to fixing the crash, it
brings the implementation in line with the one on Linux, where
duplicates are allowed.  I assume the Windows implementation also
allows duplicates, but I haven't tried it.
=> cocoa: allow duplicate choice% labels

gui-lib/mred/private/wxtabcanvas.rkt
This fixes a division by zero error when the `flat-portable` style is used with no tabs (which the contract for `tab-panel%` allows and works with at least the native style on macOS).
Failing example:
```racket
#lang racket/gui
(define f (new frame%
[label "Test"]))
(define t (new (class tab-panel%
(super-new)
(define/override (on-new-request)
(send this set '("a"))))
[parent f]
[choices '()]
[style '(no-border flat-portable new-button)]))
(send f show #t)
```
=> wxtabcanvas: fix painting with no items

.github/workflows/ci.yml, gui-lib/mred/private/wx/gtk/frame.rkt
closes #280 and fixes the ci issue
=> gtk: round down scaled arguments to make-GdkRectangle

gui-lib/mred/private/wx/cocoa/frame.rkt, gui-lib/mred/private/wx/cocoa/queue.rkt, gui-lib/mred/private/wxpanel.rkt, gui-lib/mred/private/wxtop.rkt
There is at least one problem with this pr, namely that it only requests refreshes for the frames in the original/main eventspace. I had thought of using the custodian hierarchy to reach other eventspaces but this doesn't work because I need a parent custodian that I don't have.
I'm also not sure if `queue-paint` is the right method to invoke when finding a canvas.
=> refreshing canvases when entering/leaving dark mode

.github/workflows/ci.yml, gui-doc/scribblings/gui/message-class.scrbl, gui-lib/info.rkt, gui-lib/mred/private/wx/cocoa/color.rkt, gui-lib/mred/private/wx/cocoa/message.rkt, gui-lib/mred/private/wx/gtk/message.rkt
Changes `message%` cocoa and gtk wxs to reset messages to the default color when set to an invalid color or `#f`. The win32 implementation already behaves this way.
Fixes #307
~~Draft while I set up a Linux VM to test the change there also.~~
=> message: handle invalid colors under cocoa and gtk

gui-lib/mred/private/wx/cocoa/cg.rkt, gui-lib/mred/private/wx/cocoa/panel.rkt
This seems to fix racket/drracket#644
=> adjust cocoa 'border canvas% style to react to dark mode

gui-doc/scribblings/framework/frame.scrbl, gui-lib/framework/private/frame.rkt
I'm running Ubuntu Linux with two displays. The one on the left is a laptop which I use for terminals and whatnot. Directly in front of me is a larger monitor I use for editing.
I noticed that every time I started `DrRacket` it would show up on the primary (left) screen. After some digging it appeared that the problem was in `frame:size-pref-mixin`. My test program is at the end of this description.
I believe that the issue is due to `get-display-left-top-inset` returning negative numbers in some cases. In this instance the left number is `-1920` per the following trace statement I inserted into `get-sizes/maximzed` when I was figuring this out:
```
mon 1 delta 769 x 307 left -1920 top 0 mon size 1920 x 1080
```
This fails the first `<=` test I that I have changed resulting in the window …
=> Size pref mixin

gui-lib/framework/private/color-prefs.rkt
The sample uses `#:label`, which seem to have been replaced by `#:title`.
=> Fix argument name in color scheme sample code

gui-doc/scribblings/gui/slider-class.scrbl, gui-lib/info.rkt, gui-lib/mred/private/mritem.rkt, gui-lib/mred/private/wx/cocoa/slider.rkt, gui-lib/mred/private/wx/gtk/slider.rkt, gui-lib/mred/private/wx/win32/slider.rkt, gui-lib/mred/private/wxlitem.rkt, gui-test/tests/gracket/item.rkt, gui-test/tests/gracket/windowing.rktl
Relevant to #314.
As far as I can tell, a vertical slider in `racket/gui` is top-to-bottom on all platforms. I don't know or remember why, but I agree that a bottom-to-top slider seems more useful, and probably non-`racket/gui` programs use bottom-to-top sliders everywhere. The top-to-bottom rendering is also inherent in the macOS control, at least when the range is >= 64.
To add bottom-to-top support without breaking any old programs — just in case — this commit adds an `'upward` style option alongside `'horizontal` and `'vertical`.
=> add 'upward style for slider controls

gui-lib/mred/private/wxme/text.rkt
This fixes a bug that was found [on discourse](https://racket.discourse.group/t/uncommenting-does-not-work-on-any-linux-distro-with-gnome-3/1299/6).
=> update the focus when deleting a snip that has the focus

gui-lib/mred/private/wx/cocoa/canvas.rkt
Fixes #325. The `r` argument represents the portion of the view that is "dirty", and it seems like it may be larger than the view's frame[1]. It looks like this code was already intending to use the view's frame to draw the bezel, but accidentally used the dirty rect instead.
[1]: At least on recent versions of macOS, which may explain why [this isn't a problem when using versions of Racket built on older macOS versions](https://github.com/racket/drracket/issues/652#issuecomment-1853144763).
=> cocoa,canvas: fix bezel-cell frame for FocusView

gui-test/framework/tests/racket.rkt, gui-test/info.rkt
This adds some test cases, but also a dependency on a package that's not dependedn on (or in) main-distribution-test. Is this okay, @samth (once the rhombus-prototype repo gets split up, I mean)?
=> add a few test cases that cover the basics of the highlighting of invisible parens

gui-lib/mred/private/wx/gtk/printer-dc.rkt
Fix issue #336: for unknown reasons, asynchronous printing in GTK3 generates blank pages.  Disabling asynchronous mode fixes this problem.  This change makes the main window freeze when the print dialog is popped up.  But it shouldn't be a problem.  First this is also the default behavior when the print dialog is popped up in Windows.  This change makes the behavior more consistent on different OSes.  Besides, it is reasonable to forbid editing when the contents of the editor is being printed.
=> Fix #336: Disable asynchronous mode for GTK printing.

.github/workflows/resyntax-autofixer.yml
Hopefully this fixes the failure observed [here](https://github.com/racket/gui/actions/runs/11564770291/job/32190604572).
=> Fix autofixer workflow installation process

gui-doc/scribblings/gui/dialog-funcs.scrbl
Using path? generates a link to the predicate, like the result of get-file.
=> docs: correct result contract on get-directory
