gui-lib/mred/private/wxme/text.rkt
=> Use `object-or-false=?` on snip admins.

gui-lib/mred/private/wx/gtk/menu.rkt
Fixes #74.
It's not the cleanest fix, I guess :-( but it's short enough, and solves a very irksome bug.
Hopefully this does not create any memory leaks — is it possible for the menu to disappear without calling neither `do-selected menu-item` nor `do-no-selected` ? Also, should multi-threading issues be taken into account? Racket does not normally allow sharing mutable data between threads in an unsafe way, so I suppose this implementation should be okay without the need for further caution.
=> Pin the menu object while it is displayed, so that it is not garbage-collected

gui-lib/framework/private/color-prefs.rkt
Preferences -> Colors -> Racket and rest
Signed-off-by: Alexander Shopov <ash@kambanaria.org>
=> Start using the translation for font smoothing

gui-lib/framework/private/autocomplete.rkt
The original comparator is not asymmetric, which leads to confusing results. 
For example, when I enter "define-syntax-", "syntax" is usually more preferred than "define-syntax-rule" on my machine.
The old one:
```
> (define comp
(match-lambda**
[((cons w r) (cons w* r*))
(or (> r r*)
;; prefer shorter matches
(< (string-length w) (string-length w*)))]))
> (comp '("define-syntax-rule" . +inf.0) '("syntax" . 2))
#t
> (comp '("syntax" . 2) '("define-syntax-rule" . +inf.0))
#t
```
=> make comparator for autocompletion candidates asymmetric

gui-lib/mred/private/wx/win32/clipboard.rkt, gui-lib/mred/private/wx/win32/hbitmap.rkt
Fixes https://github.com/racket/racket/issues/2273
=> Added alpha-channel to paste from clipboard

gui-lib/mred/private/wx/cocoa/cgl.rkt
=> gl-bitmap respects legacy setting on gl-config%

gui-doc/scribblings/gui/horizontal-panel-class.scrbl, gui-doc/scribblings/gui/vertical-panel-class.scrbl
Documentation: adds the 'hide-hscroll and 'hide-vscroll style parameters from panel% to vertical-panel% and horizontal-panel%
=> horizontal-/vertical-panel% make style parameters consistent with panel%

gui-lib/mred/private/wxme/editor-canvas.rkt
This significantly improves trackpad scrolling responsiveness for me on macOS. I don't have a mouse to test with or any Windows or Linux machines so it would be helpful if folks with access to any of those things could give this a spin.  Steps to test:
1. clone this repo and checkout this commit
2. run `raco pkg update --link gui-lib` from the repository root
3. run `racket -l drracket` and open a large file
4. scroll around
Scrolling is still a little laggy when there are multiple tabs open. I'm not sure why that is yet.
=> improve editor-canvas% scrolling responsiveness

gui-lib/framework/main.rkt, gui-lib/framework/private/color-prefs.rkt, gui-lib/framework/private/sig.rkt
Having a predicate for this type makes things easier to describe
in the type system.
=> Add `color-prefs:color-scheme-color-name?` to help TR.

gui-lib/framework/private/racket.rkt, gui-test/framework/tests/racket.rkt
=> fixes auto-parens when typing quote or bar near comments/strings

gui-lib/framework/private/racket.rkt, gui-test/framework/tests/racket.rkt
=> Fixes auto-parens for double quote before later double quote string

gui-doc/scribblings/framework/racket.scrbl
Added text to tabify-all and indentation-mumble, per email discussion
=> add note about indentation and graphical context

gui-doc/scribblings/gui/dialog-class.scrbl
Consolidate descriptions of each possibility for `show?` argument
=> docs for `show`: undo miscorrection & clarify

gui-lib/framework/main.rkt, gui-lib/framework/srcloc-snip.rkt
This unbreaks the load.rkt test.
=> Unbreak load

gui-lib/framework/private/text-port.rkt
I just added `image-markup` to `simple-tree-text-markup/data`. This is the rendering support for that.
(I'm not really happy with `record-dc-datum->bitmap` as there's no predicate for the `record-dc%` data.)
=> Handle image-markup

gui-lib/mred/private/wxme/text.rkt
=> fix clipping rect for nested text

gui-doc/scribblings/gui/message-class.scrbl, gui-lib/info.rkt, gui-lib/mred/private/mritem.rkt, gui-lib/mred/private/wx/cocoa/color.rkt, gui-lib/mred/private/wx/cocoa/colordialog.rkt, gui-lib/mred/private/wx/cocoa/message.rkt, gui-lib/mred/private/wx/gtk/message.rkt, gui-lib/mred/private/wx/win32/message.rkt, gui-lib/mred/private/wx/win32/utils.rkt, gui-lib/mred/private/wx/win32/window.rkt, gui-lib/mred/private/wxitem.rkt
The CI failure is expected since the GTK change depends on a change to `draw-lib`.
=> message%: add support for text colors

gui-lib/framework/private/keymap-global.rkt
=> More logical Greek keybindings

gui-lib/mred/private/wx/gtk/message.rkt
=> update gtk icon apis and stock file names per the gtk doc

gui-lib/mred/private/wx/gtk/frame.rkt
`gdk_screen_get_monitor_geometry` is supposed to return the logic size of a
display. However, due to the upstream bug [1], we have to manually recalculate
the size.
[1] https://gitlab.gnome.org/GNOME/gtk/-/issues/2599
=> scaling: work around an upstream bug on wayland

gui-lib/mred/private/messagebox.rkt
https://github.com/racket/gui/commit/ac6b4b81241cabf56600e5a7f7e167e9c6aea7d3#r49116626
=> React to message-box resizing (on non-macos)

gui-doc/info.rkt, gui-doc/mrlib/scribblings/interactive-value-port.scrbl, gui-doc/scribblings/gui/init.scrbl
Related to racket/racket#3215.
=> Reduce dependencies.

gui-lib/mred/private/wx/gtk/frame.rkt, gui-lib/mred/private/wx/gtk/style.rkt
Things I wonder about:
- Is the deallocation of the value in `the-text-style` right?
- Is it okay to add one more set of declarations for `_GtkSettings` and related things (in style.rkt)?
- Should there be some versioning guards somewhere in this code?
And, of course, using a regular expression on the name of the theme also seems somewhat sketchy but I'm not able to turn up something better.
=> Update gtk to react to dark mode changes

gui-lib/mred/private/wx/cocoa/key-translate.rkt
=> Repair for Issue #330

.github/workflows/resyntax-autofixer.yml
This broke the autofixer runs.
=> Fix typo in resyntax-autofixer.yml
